// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAINzpOrZKs8dQx9fnpm8v7-xTmMFAosA0',
    appId: '1:933185336061:web:088d50d7b54d3f16b1c494',
    messagingSenderId: '933185336061',
    projectId: 'cinemareserve-2bce9',
    authDomain: 'cinemareserve-2bce9.firebaseapp.com',
    storageBucket: 'cinemareserve-2bce9.appspot.com',
    measurementId: 'G-HKRW7D37V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgRsKq71aBHGe_MWD-1-bORIZ8C77o04Y',
    appId: '1:933185336061:android:88d276d4228b5a24b1c494',
    messagingSenderId: '933185336061',
    projectId: 'cinemareserve-2bce9',
    storageBucket: 'cinemareserve-2bce9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsLxFvaFzLv7TIpmxPvbOv40eUawqD0zg',
    appId: '1:933185336061:ios:938f5608bf70d6d1b1c494',
    messagingSenderId: '933185336061',
    projectId: 'cinemareserve-2bce9',
    storageBucket: 'cinemareserve-2bce9.appspot.com',
    iosBundleId: 'com.example.cineReserveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsLxFvaFzLv7TIpmxPvbOv40eUawqD0zg',
    appId: '1:933185336061:ios:a389ddebefc1dcd5b1c494',
    messagingSenderId: '933185336061',
    projectId: 'cinemareserve-2bce9',
    storageBucket: 'cinemareserve-2bce9.appspot.com',
    iosBundleId: 'com.example.cineReserveApp.RunnerTests',
  );
}
